- name: Update repositories cache and install "sysbench" package
  apt:
    name: sysbench
    update_cache: yes

- name: Creates result directory
  file:
    path: /home/ubuntu/result/
    state: directory


- name: Execute CPU test
  shell: "sysbench --test=cpu --num-threads=1 --cpu-max-prime=1000 --time=0 --events=1000 run > /home/ubuntu/result/sysbench-cpu-test"

- name: Fetch cpu test data
  ansible.builtin.fetch:
    src: /home/ubuntu/result/sysbench-cpu-test
    dest: ../../../results/test-result-{{ PROVISION_TYPE }}/
    flat: yes


- name: Execute RAM test
  shell: "sysbench --num-threads=1 --test=memory --time=0 --memory-block-size=1M --memory-total-size=100G run > /home/ubuntu/result/sysbench-ram-test"

- name: Fetch ram test data
  ansible.builtin.fetch:
    src: /home/ubuntu/result/sysbench-ram-test
    dest: ../../../results/test-result-{{ PROVISION_TYPE }}/
    flat: yes


- name: Execute SEQ-IO test
  shell: "sysbench --test=fileio --file-total-size=5G --file-num=100 prepare > /home/ubuntu/result/sysbench-seq-io-test"

- name: Fetch SEQ-IO test data
  ansible.builtin.fetch:
    src: /home/ubuntu/result/sysbench-seq-io-test
    dest: ../../../results/test-result-{{ PROVISION_TYPE }}/
    flat: yes

- name: Delete Seq-IO-testfiles
  shell: /bin/rm -rf /home/ubuntu/test_file.*


- name: Prepair ASEQ-IO test
  shell: "sysbench --test=fileio --file-total-size=4096000K --file-block-size=4096K --file-num=1000 --num-threads=1 --max-requests=0 --max-time=300 --file-extra-flags=direct --file-test-mode=rndrd prepare"

- name: Execute ASEQ-IO test
  shell: "sysbench --test=fileio --file-total-size=4096000K --file-block-size=4096K --file-num=1000 --num-threads=1 --max-requests=0 --max-time=300 --file-extra-flags=direct --file-test-mode=rndrd run > /home/ubuntu/result/sysbench-aseq-io-test"

- name: Fetch ASEQ-IO test data
  ansible.builtin.fetch:
    src: /home/ubuntu/result/sysbench-aseq-io-test
    dest: ../../../results/test-result-{{ PROVISION_TYPE }}/
    flat: yes